kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-storage-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-storage-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
