production:
  type: ocp
  bundle:
    registry: quay.io
    organization: vrutkovs
  index:
    registry: quay.io
    organization: vrutkovs
    name: catalog_tmp
    tags:
      - v4.12-db
    latest: ""
    signature:
      enabled: 0
      alias: not-defined
      endpoint: https://not-defined

pipeline:
  base: https://github.com
  repo: vrutkovs/okd-operators
  branch: main
  ci_scripts_dir: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts
  image: quay.io/operator_testing/operator-test-playbooks:latest
  playbooks:
    repo: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks
    branch: "upstream-community"
  automerge:
    enabled: 1
  reviewers:
    enabled: 1
  notifications:
    slack: 1

operatorhubio:
  enabled: 0

#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.9.0
  kind_kube_version: v1.21.1
  operator_sdk_version: v1.8.0
